version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "3001:3001"
      - "3002:3002"
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb

  web-ui:
    build: ./web-ui
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command:
      [
        "mongod",
        "--logpath=/var/log/mongodb/mongod.log",
        "--setParameter",
        "logLevel=1",
      ]
  
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    volumes:
      - libsql-data:/var/lib/libsql

volumes:
  mongo-data:
  libsql-data:
