version: '3.8'

x-common: &common-configuration
  restart: always
  environment:
    - SECRET_KEY=${SECRET_KEY}
  volumes:
    - ./shared:/usr/src/app/shared
  depends_on:
    - mongodb

services:
  auth:
    build: ./auth
    ports:
      - '3000:3000'
    <<: *common-configuration

  user:
    build: ./user
    ports:
      - '3001:3001'
    <<: *common-configuration

  catalog:
    build: ./catalog
    ports:
      - '3002:3002'
    <<: *common-configuration
    volumes:
      - ./media/contentData.json:/usr/src/app/contentData.json
      - ./media/static:/usr/src/app/static
      - ./shared:/usr/src/app/shared

  watchlist:
    build: ./watchlist
    ports:
      - '3003:3003'
    <<: *common-configuration

  streaming:
    build: ./streaming
    ports:
      - '1935:1935'
      - '8003:8003'
    <<: *common-configuration
    volumes:
      - ./media:/usr/src/app/media

  web-ui:
    build: ./web-ui
    ports:
      - '3004:3000'
    # environment:
    #   - NODE_ENV=development
    # volumes:
    #   - ./web-ui:/usr/src/app

  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--logpath=/var/log/mongodb/mongod.log", "--setParameter", "logLevel=1"]

  kong:
    image: kong:3.8
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_LOG_LEVEL: "warn"
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"   # Proxy
      - "8001:8001"   # Admin API
    volumes:
      - ./kong/declarative:/kong/declarative
    depends_on:
      - auth
      - user
      - catalog
      - watchlist
      - streaming
    restart: always

volumes:
  mongo-data: